apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.16.1
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: http
          port: 9200
          nodePort: 30920
    tls:
      selfSignedCertificate:
        disabled: true  
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      xpack.security.authc:
                anonymous:
                  username: anonymous
                  roles: superuser
                  authz_exception: false