apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      tcp {
          port => "5044"
          codec => json
      }
    }
    output {
      elasticsearch {
        hosts => ["http://quickstart-es-http:9200"]
        index => "logging-spring-log-%{+YYYY.MM.dd}"
      }
    }    
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30504
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.16.2
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
